export default {
    FETCH_HEADER_USER_REQUEST: 'FETCH_HEADER_USER_REQUEST',
    FETCH_HEADER_USER_SUCCESS: 'FETCH_HEADER_USER_SUCCESS',
    FETCH_HEADER_USER_FAILURE: 'FETCH_HEADER_USER_FAILURE',
    FETCH_USERS_REQUEST: 'FETCH_USERS_REQUEST',
    FETCH_USERS_SUCCESS: 'FETCH_USERS_SUCCESS',
    FETCH_USERS_FAILURE: 'FETCH_USERS_FAILURE',
    LOAD_MORE_USERS_REQUEST: 'LOAD_MORE_USERS_REQUEST',
    LOAD_MORE_USERS_SUCCESS: 'LOAD_MORE_USERS_SUCCESS',
    LOAD_MORE_USERS_FAILURE: 'LOAD_MORE_USERS_FAILURE',
    FETCH_POSITIONS_REQUEST: 'FETCH_POSITIONS_REQUEST',
    FETCH_POSITIONS_SUCCESS: 'FETCH_POSITIONS_SUCCESS',
    FETCH_POSITIONS_FAILURE: 'FETCH_POSITIONS_FAILURE',
}